#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules"]

index = {"get_addr": "00_markdownmail.ipynb",
         "md2email": "00_markdownmail.ipynb",
         "MarkdownMailMerge": "00_markdownmail.ipynb"}

modules = ["markdownmailmerge.py"]