# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/markdown_merge',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/markdown_merge',
                'lib_path': 'markdown_merge'},
  'syms': { 'markdown_merge.core': { 'markdown_merge.core.MarkdownMerge': ('core.html#markdownmerge', 'markdown_merge/core.py'),
                                     'markdown_merge.core.MarkdownMerge.__init__': ( 'core.html#markdownmerge.__init__',
                                                                                     'markdown_merge/core.py'),
                                     'markdown_merge.core.MarkdownMerge.reset': ('core.html#markdownmerge.reset', 'markdown_merge/core.py'),
                                     'markdown_merge.core.MarkdownMerge.send_msgs': ( 'core.html#markdownmerge.send_msgs',
                                                                                      'markdown_merge/core.py'),
                                     'markdown_merge.core.attach_file': ('core.html#attach_file', 'markdown_merge/core.py'),
                                     'markdown_merge.core.create_multipart_msg': ( 'core.html#create_multipart_msg',
                                                                                   'markdown_merge/core.py'),
                                     'markdown_merge.core.get_addr': ('core.html#get_addr', 'markdown_merge/core.py'),
                                     'markdown_merge.core.md2email': ('core.html#md2email', 'markdown_merge/core.py'),
                                     'markdown_merge.core.smtp_connection': ('core.html#smtp_connection', 'markdown_merge/core.py')}}}
