# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/',
                'doc_host': 'https://answerdotai.github.io',
                'git_url': 'https://github.com/answerdotai/markdown_merge/tree/master/',
                'lib_path': 'markdown_merge'},
  'syms': {'markdown_merge.markdown_merge': {}}}
