#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules"]

index = {"get_addr": "00_markdown_merge.ipynb",
         "md2email": "00_markdown_merge.ipynb",
         "MarkdownMerge": "00_markdown_merge.ipynb"}

modules = ["markdown_merge.py"]